version: '3.8'

services:
  #ssh -L 11434:127.0.0.1:11434 -p 2222 models@localhost
  ollama:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama
    ports:
      - 3000:8080
    networks:
      - traefik-public

  vps-ollama:
    build: .
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - ollama-Makefile:/home/models/Makefile
      - ollama-data:/home/models
      - ollama:/usr/local/bin
    networks:
      - traefik-public
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  #ssh -L 7865:127.0.0.1:7865 -p 2223 models@localhost
  vps-foocus:
    build: .
    privileged: true
    ports:
      - "2223:22"
    volumes:
      - vps-foocus-Makefile:/home/models/Makefile
      - vps-foocus-data:/home/models
    networks:
      - traefik-public
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  #ssh -L 7860:127.0.0.1:7860 -p 2224 models@localhost
  vps-diffusion:
    build: .
    privileged: true
    ports:
      - "2224:22"
    volumes:
      - vps-diffusion-Makefile:/home/models/Makefile
      - vps-diffusion-data:/home/models
    networks:
      - traefik-public
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama:
  ollama-data:
  ollama-Makefile:
  vps-diffusion-Makefile:
  vps-diffusion-data:
  vps-foocus-Makefile:
  vps-foocus-data:

networks:
  traefik-public:
    external: true
